---
- name: Get systemd version
  ansible.builtin.shell: |
    set -eo pipefail
    systemd --version | head -n 1 | awk '{ print $2 }'
  changed_when: false
  check_mode: false
  register: prometheus__reg_systemd_version
  tags:
    - prometheus

- name: Check if systemd version is valid
  ansible.builtin.assert:
    that:
      - prometheus__reg_systemd_version.stdout | int >= prometheus_minimum_systemd_version | int
  tags:
    - prometheus

- name: Create system group
  become: true
  ansible.builtin.group:
    name: prometheus
    system: true
    state: present
  tags:
    - prometheus
    - alertmanager

- name: Create system user
  become: true
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    home: "{{ prometheus_db_dir }}"
  tags:
    - prometheus
    - alertmanager

- name: Create configuration directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: "0770"
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"
  tags:
    - prometheus
    - alertmanager

- name: Prometheus | import tasks
  ansible.builtin.import_tasks:
    file: prometheus.yml
  tags: prometheus

- name: Alertmanager | import tasks
  ansible.builtin.import_tasks:
    file: alertmanager.yml
  tags: alertmanager
