---
- name: Prometheus | Create data directory
  become: true
  ansible.builtin.file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Prometheus | Download
  ansible.builtin.get_url:
    url: "{{ prometheus__download_url }}"
    dest: /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    mode: "0644"
  retries: 5
  delay: 3

- name: Prometheus | Unpack
  become: true
  ansible.builtin.unarchive:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: true
    owner: root
    group: root

- name: Prometheus | Copy binaries
  become: true
  ansible.builtin.copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}
    dest: "{{ prometheus_binary_dir }}"
    mode: "0755"
    owner: root
    group: root
    remote_src: true
  loop:
    - prometheus
    - promtool
  notify:
    - Restart prometheus

- name: Prometheus | Copy config
  become: true
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: "0644"
    owner: root
    group: root
    validate: "{{ prometheus_binary_dir }}/promtool check config %s"
  notify:
    - Restart prometheus

- name: Prometheus | Copy rules
  become: true
  ansible.builtin.template:
    src: rules.yml.j2
    dest: "{{ prometheus_config_dir }}/rules/rules.yml"
    mode: "0644"
    owner: root
    group: root
    validate: "{{ prometheus_binary_dir }}/promtool check rules %s"

- name: Prometheus | Configure web config
  become: true
  ansible.builtin.copy:
    content: "{{ prometheus_web_config | to_nice_yaml(indent=2, sort_keys=False) }}"
    dest: "{{ prometheus_config_dir }}/web.yml"
    force: true
    owner: root
    group: prometheus
    mode: "0640"
    validate: "{{ prometheus_binary_dir }}/promtool check config %s"

- name: Prometheus | Copy service definitions
  become: true
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart prometheus

- name: Prometheus | Ensure prometheus is started and enabled
  become: true
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
  retries: 3
  delay: 2
